language: node_js
node_js:
- "8.9.1"
install:
- npm install
script:
- make clean
- make
- make test
notifications:
  email:
    recipients:
      - kirkins@gmail.com
    on_success: never
on_failure: always
